version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
  pre_build:
    commands:
      - cd $lambda
      - pip install -r requirements.txt
artifacts:
    files:
      - '$lambda/*'
    name: $lambda