version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
  pre_build:
    commands:
      - cd hello-world
      - pip install -r requirements.txt
artifacts:
    files:
      - 'hello-world/*'
    name: hello-world